// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOzn_CJtDoxGaggxICq2CvPr2UfEK_UoU',
    appId: '1:381206905366:web:df0b3fa8aa0433749d2b37',
    messagingSenderId: '381206905366',
    projectId: 'uasapp1-493ca',
    authDomain: 'uasapp1-493ca.firebaseapp.com',
    storageBucket: 'uasapp1-493ca.appspot.com',
    measurementId: 'G-QE9565QSVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIe1wQ14mC1lwecAFr-hfnirieGjQCSSU',
    appId: '1:381206905366:android:9c33c58a723d442e9d2b37',
    messagingSenderId: '381206905366',
    projectId: 'uasapp1-493ca',
    storageBucket: 'uasapp1-493ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtd76ubwA_XAMVK8Nv3XEW2b5dBK2SNEA',
    appId: '1:381206905366:ios:fe6e474c27c243999d2b37',
    messagingSenderId: '381206905366',
    projectId: 'uasapp1-493ca',
    storageBucket: 'uasapp1-493ca.appspot.com',
    iosBundleId: 'com.example.uasRentalMobilApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtd76ubwA_XAMVK8Nv3XEW2b5dBK2SNEA',
    appId: '1:381206905366:ios:c52741794103d5689d2b37',
    messagingSenderId: '381206905366',
    projectId: 'uasapp1-493ca',
    storageBucket: 'uasapp1-493ca.appspot.com',
    iosBundleId: 'com.example.uasRentalMobilApp.RunnerTests',
  );
}
